---
title: "課?<a0>?練習模<e7><89><88>"
author: "AnWen"
date: "2020-12-13"
output: output_format
params:
  id: "410873022"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code
Regular expression
(regex)
一種廣義描述所要字串規律及在字句位置的表示法
```{r}
Rmdfiles <- c("file1.Rmd", "file2.R", "file3.rmd", "file4.RMD", "myRmd.R")#rmd是副檔名
SchoolIds <- c("410973029", "410988011", "410974023","410783025","710773022","410788021","410673124","410873051","49988001")#不可能用一個數字描述完
library(glue)
library(stringr)
```
目標規律性描述#若有出現目標,他長怎樣
目標位置註解#先描述目標,再定位
#使用[ ]來定義字元卷帶
```{r}
Rmdfiles
regexPattern="[Rr][Mm][Dd]"
str_subset(Rmdfiles, pattern=regexPattern)#選出符合pattern的


```
#不分大小寫
```{r}
str_subset(
  Rmdfiles,pattern = regex("rmd",ignore_case = T)
)
```

#(.)字組是phrace
```{r}
SchoolIds
regexPattern="[4](108|109)(73|88)"
str_subset(
  SchoolIds, pattern=regexPattern)

```
萃取
```{r}
sameIdentities <- c("臺北市", "台北市", "台北大學", "臺北大學", "基隆市")
#要不要向量
str_detect(
  sameIdentities, pattern="[台臺]")
str_view_all(
  sameIdentities, pattern="[台臺]")
```
```{r}
#符合地拉出來
str_extract(
  sameIdentities, pattern="[台臺]北市")
```
```{r}
dragonPeople <-
  c(
    "住在台北市的臺北人也常被稱為天龍人")
str_extract(
  dragonPeople,
  pattern="[台臺]北[市人]"
)#只拿台北市
# 當一個元素值內的文字規律可多次出現時用_all來一網打盡，否則只處理第一個出現的規律
str_extract_all(
  dragonPeople,
  pattern="[台臺]北[市人]"
)
```
```{r}
Rmdfiles # length=5
str_replace(
  Rmdfiles,
  pattern = rep("[Rr][Mm][Dd]",5),
  replacement = rep("Rmd",5)
)
```
#pattern與replacement長度與string不同時會進行recycle
```{r}
Rmdfiles # length=5
str_replace(
  Rmdfiles,
  pattern = "[Rr][Mm][Dd]",
  replacement = "Rmd"
)
```
#不同規律要做不同替換時使用
```{r}
str_replace_all(
  string,
  c(
    "pattern1"="replacement1",
    "pattern2"="replacement2",
    
  )
)
```
```{r}
emailContent <- '親愛的_name_朋友好，

  恭喜你，你的電子發票號碼_invoiceNumber_ 差點中獎。'
cat(emailContent)
```
```{r}
replacementNamedVector <- c(
  "_name_" = "小新",
  "_invoiceNumber_" = "EF-89400133"
)

synthesizedContent <- str_replace_all(
  emailContent,
  replacementNamedVector
)
cat(synthesizedContent)
```

```{r}
set.seed(2020)
d1 <- sample(c(rep("4",10),rep("3",3),rep("7",3)), 25, replace=T)
d2 <- sample(98:109, 25, replace=T)
d3 <- sample(c("73", "74", "78", "83", "72"))
d4 <- sample(1:120, 25, replace=T)
d4 <- str_pad(d4, 3, side = "left", pad="0")
schoolIds <- paste0(d1,d2,d3,d4)
schoolIds
```
#捲帶裝幾條
```{r}
# {x} 前方卷帶連裝x條
str_subset(schoolIds,
           pattern='[0123456789]{9}')
str_subset(schoolIds,
           pattern='[0-9]{9}')
str_subset(schoolIds,
           pattern='[:digit:]{9}')
```
```{r}
myLove2R <- c("我實在是太愛太愛太愛愛R課程了",
  "我才是太愛太愛太太愛太太太愛R了",
  "我則是太愛愛太愛太愛愛愛R了",
  "找我太太聊天，我太太愛理不理的，我只好回去練我最愛的R。")
```
```{r}
str_view_all(myLove2R,"(太愛){2}")#(),否則太愛愛
```

```{r}
str_view_all(myLove2R, "太[愛]*")
```
目標位置註解
```{r}
str_view_all(myLove2R, "太愛[愛]?")
```
```{r}
#! is not
```
```{r}
addresses <- c(
  '臺中市后里區公館里尾社路385號',
  '新竹市東區科學園路125號1樓',
  '新竹市北區竹光路99號',
  '金門縣金城鎮賢庵里山前33號',
  '臺中市南屯區工業區二十四路23號1樓')
```

```{r}
str_extract(
  addresses,
  "(?<=[縣市])[\u4E00-\u9FFF]+[區鎮]"
)#what in the front is 縣或市
```
#[^XYZ]：要排除的字元XYZ
```{r}
str_extract(
  addresses,
  "(?<=[縣市])[^區]+[區鎮]"
)
```
#在開頭：^目標 （不要和字元排除卷帶[^XYZ]搞混）

#在結尾：目標$
```{r}
Rmdfiles <- c("file1.Rmd", "file2.R", "file3.rmd", "file4.RMD", "myRmd.R")
```
```{r}
str_subset(
  Rmdfiles, "[Rr][Mm][Dd]"
)

# 要求在句尾
str_subset(
  Rmdfiles, "[Rr][Mm][Dd]$"
)
```
```{r}
download.file("https://www.dropbox.com/s/o9kt3lxtx9pmjqj/homework2.Rmd?dl=1", destfile = "./hw2.Rmd", mode="wb")
xfun::read_utf8("./hw2.Rmd") -> hw2lines
View(hw2lines)
```
```{r}
pick_starting3Hash <- str_detect(
  hw2lines,
  "^###"
)
sum(pick_starting3Hash)
```
```{r}
pick_starting3Hash <- str_detect(
  hw2lines,
  "^### (?=[0-9])"
)
sum(pick_starting3Hash)
```
```{r}

```





